# sonar.exclusions=**/*.js,**/*.json,**/*.xml,**/*.png,**/*.sh,**/*.h,**/*.m,**/*.c,**/*.cpp,**/*.pdf,**/*.plist,Pods/**/*
# sonar.swift.excludedPathsFromCoverage=.*Tests.*
sonar.exclusions=\
create.js,\
src/global/fcm/firebase-project-service.json,\
src/route/core/setting/schemas/setting.schema.ts,\
public/assets/css/style.css,\
src/global/storage/storage.service.ts,\
src/route/core/endpoint-ui-admin/endpoint-ui-admin.service.ts,\
src/global/seed/province.seeder.ts,\
src/base-module/base.repository.ts,\
src/route/core/monitor-health/monitor-health.service.ts,\
src/route/core/rbac-api/rbac-api.service.ts,\
src/route/core/setting/setting.service.ts,\
src/route/core/upload/upload.service.ts,\
src/util/filter/all-exceptions.filter.ts,\
src/util/guard/role.guard.ts,\
src/util/interceptor/aqp/aqp.middleware.ts